apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.serviceProviderClassName }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secretName }}
      data:
        {{- range .Values.secretObjects }}
        - key: {{ tpl .key $ }}
          objectName: {{ tpl .objectName $ }}
        {{- end }}
      type: {{ .Values.secretType }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.keyvaultName }}"
    cloudName: ""
    objects: |
      array:
      {{- range .Values.secrets }}
        - |
          objectName: {{ tpl .name $ }}
          objectType: secret
      {{- end }}
    tenantId: "{{ .Values.tenantId }}"